### ISSUE TITLE
Magic 8 Ball / coin flip feature

### ISSUE THREAD

**Issue by Dethrimme** [seancallaway/drollerbot#6]
It'd be interesting to have a feature that mimics decision making. For side humor during DnD sessions as well as in-between games. For example, if I were to inquire if Sean would finally give in and play Diablo 3, I could type .magic8ball and receive a response, instead of googling for one. Please private message for further examples.

**Comment by seancallaway** [comment]
Coin flip can be done by rolling a d2 (i.e. `.roll 1d2`).

**Comment by seancallaway** [comment]
Now working live via `.magic8ball` command.
